# VOICEVOXの公式CPU版イメージをベースにする
FROM voicevox/voicevox_engine:cpu-latest



# 作業ディレクトリの設定
WORKDIR /scr

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    locales \
    ffmpeg \
    python3.11 \
    python3.11-venv \
    python3.11-dev \
    python3-pip \
    supervisor \
    && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8 \
    && python3.11 -m pip install --upgrade pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 環境変数の設定
ENV LANG=ja_JP.UTF-8 \
    LANGUAGE=ja_JP:ja \
    LC_ALL=ja_JP.UTF-8 \
    TZ=Asia/Tokyo \
    TERM=xterm

# Pythonパッケージのインストール
COPY requirements.txt .
RUN python3.11 -m pip install --no-cache-dir -r requirements.txt

# アプリケーションのコードをコピー
COPY . .

# start.shを実行可能にする
RUN chmod +x /scr/start.sh

# ポートの開放
EXPOSE 50021
EXPOSE 8080

# start.shを使ってvoicevoxとPythonプログラムを起動
CMD ["/scr/start.sh"]
